window.PEOPLE_DIRECTORIES = {
  "core": [
    {
      "name": "Badri Narayanan Gopalakrishnan, PhD",
      "role": "Founder",
      "image": "https://infisum.com/wp-content/uploads/2024/02/63f70ebf39759c38eb11669b_Athena-Infonomics-People-Advisor-Dr.-Badri-Narayanan-Gopalakrishnan.jpeg",
      "linkedin": "https://www.linkedin.com/in/badrinarayanang/",
    },
    {
      "name": "Sumathi Chakravarthy",
      "role": "Managing Director",
      "image": "https://infisum.com/wp-content/uploads/2020/05/SumathiChakravarthy.png",
      "linkedin": "https://www.linkedin.com/in/sumathi-chakravarthy-1929812a",
    },
    {
      "name": "Divyayudha Khire",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2022/03/WhatsApp-Image-2022-03-24-at-3.16.04-PM.jpeg",
      "linkedin": "https://www.linkedin.com/in/divyayudha-khire-5020651a8",
    },
    {
      "name": "C Karthikeyan",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2023/02/WhatsApp-Image-2023-02-02-at-11.20.13.jpg",
      "linkedin": "https://www.linkedin.com/in/karthikeyan-chandramohan-52a2aa42",
    },
    {
      "name": "Nambu Narayani N",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2023/04/1682046470726-scaled.jpg",
      "linkedin": "https://www.linkedin.com/in/nambu-narayani-66609a211",
    },
    {
      "name": "Asha Abraham",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2024/03/1577994525304.jpg",
      "linkedin": "https://www.linkedin.com/in/asha-abraham/",
    },
    {
      "name": "Ajayanand Chari",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2024/07/1672126518753.jpeg",
      "linkedin": "https://www.linkedin.com/in/ajayanand-chari-11420425b/",
    },
    {
      "name": "Dr. Spencer Cohen",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2020/10/spencer-cohen-headshot_750xx576-325-0-193.jpg",
      "linkedin": "https://www.linkedin.com/in/spencer-cohen-phd-%E6%9F%AF%E8%A5%BF%E6%9C%AC-%E5%8D%9A%E5%A3%AB-4651469",
    },
    {
      "name": "Dr. Manitra A.Rakotoarisoa",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2020/05/Dr.-Manitra-A.-Rakotoarisoa.jpg",
      "linkedin": "",
    },
    {
      "name": "Krithika Shankaran",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2023/08/1663160742772.jpeg",
      "linkedin": "https://www.linkedin.com/in/krithika-shankaran-9bb548b8",
    },
    {
      "name": "Sathya Krishnasamy",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2024/04/1550883204403.jpg",
      "linkedin": "https://www.linkedin.com/in/sathya-krishnasamy-3b369a20/",
    },
    {
      "name": "Dr. Rahul Sen",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2020/05/advisors-32.jpg",
      "linkedin": "https://www.linkedin.com/in/rahul-sen-39a7741a/",
    },
    {
      "name": "Chandni Dawani",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2023/06/1620899691207-1.jpeg",
      "linkedin": "https://www.linkedin.com/in/chandni-dawani-613431b4/",
    },
    {
      "name": "Chris Clague",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2023/12/1517711627404.jpeg",
      "linkedin": "https://www.linkedin.com/in/chris-clague-6a8a996/",
    },
    {
      "name": "Dr. Sadhana Srivastava",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2020/09/Dr.Sadhana.jpg",
      "linkedin": "https://www.linkedin.com/in/sadhana-srivastava-phd-59210125/",
    },
    {
      "name": "Dr. Martina Dove",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2024/06/1676600152491.jpeg",
      "linkedin": "https://www.linkedin.com/in/martina-dove",
    },
    {
      "name": "Ashutosh Tiwari",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2024/07/1687818742012.jpeg",
      "linkedin": "https://www.linkedin.com/in/ashutosh-tiwari-74768a62",
    },
    {
      "name": "A.K.Misra",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2024/07/WhatsApp-Image-2024-07-05-at-23.17.01_3f873576-1.jpg",
      "linkedin": "https://www.linkedin.com/in/akhilesh-misra-ak-ms-mba-cssbb-00461210",
    },
    {
      "name": "Joydeep Hazra",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2024/10/1563214990907.jpeg",
      "linkedin": "https://www.linkedin.com/in/joydeeph/",
    },
    {
      "name": "Jalpan Dave",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2024/10/1708332366855.jpeg",
      "linkedin": "https://www.linkedin.com/in/jalpan-dave/",
    },
    {
      "name": "Vibhu Rakesh",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2024/10/1682926995401.jpeg",
      "linkedin": "https://www.linkedin.com/in/vibhu-rakesh-27705a62/",
    },
    {
      "name": "Anjela Arora",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2024/10/1608780705666.jpeg",
      "linkedin": "https://www.linkedin.com/in/anjela-arora",
    },
    {
      "name": "Anjali Sharma",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2024/10/1645793320921.jpeg",
      "linkedin": "https://www.linkedin.com/in/anjali-sharma-568051197/",
    },
    {
      "name": "Adhitya Balasubramaniyan",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2021/10/Adhitya-297x300.jpg",
      "linkedin": "",
    },
    {
      "name": "Anoushka Chawla",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2021/09/demo-intern-300x242.png",
      "linkedin": "https://in.linkedin.com/in/anoushkachawla",
    },
    {
      "name": "Govind Gupta",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2021/09/demo-intern-300x242.png",
      "linkedin": "https://in.linkedin.com/in/govind-gupta-9559481b0",
    },
    {
      "name": "Miheer Jain",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2021/10/Miheer.jpg",
      "linkedin": "https://in.linkedin.com/in/miheer-j-488384a8",
    },
    {
      "name": "Samarth Khurana",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2021/09/demo-intern-300x242.png",
      "linkedin": "https://in.linkedin.com/in/khuranasamarth",
    },
    {
      "name": "Anish Uppal",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2021/10/Anish-Uppal-284x300.jpg",
      "linkedin": "https://in.linkedin.com/in/anish-uppal",
    },
    {
      "name": "Arghya Nandi",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2021/09/demo-intern-300x242.png",
      "linkedin": "https://in.linkedin.com/in/arghya-nandi-1737641b4",
    },
    {
      "name": "Ishan Kashyap Hazarika",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2021/09/demo-intern-300x242.png",
      "linkedin": "https://www.linkedin.com/in/ishan-kashyap-hazarika-541554170",
    },
    {
      "name": "Rashmi Kundu",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2021/10/Rashmi.jpg",
      "linkedin": "",
    },
    {
      "name": "Sandesh Dhlokia",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2021/09/demo-intern-300x242.png",
      "linkedin": "https://in.linkedin.com/in/sandesh-dholakia",
    },
    {
      "name": "Anshul Vats",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2021/10/Anshul-Vats.jpg",
      "linkedin": "",
    },
    {
      "name": "Aswathi Ajayan",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2021/10/Aswathi-Ajayan-300x300.jpg",
      "linkedin": "https://ae.linkedin.com/in/aswathi-ajayan",
    },
    {
      "name": "Lakshita Shankar",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2021/09/demo-intern-300x242.png",
      "linkedin": "https://uk.linkedin.com/in/lakshita-shankar",
    },
    {
      "name": "Revati kanvinde",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2021/10/Revati.jpg",
      "linkedin": "https://in.linkedin.com/in/revatikanvinde01",
    },
    {
      "name": "Shreyashi Mandal",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2021/09/demo-intern-300x242.png",
      "linkedin": "",
    },
    {
      "name": "Anushka Mehta",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2021/09/demo-intern-300x242.png",
      "linkedin": "https://www.linkedin.com/in/anushka-mehta-profile",
    },
    {
      "name": "Brenda V",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2021/09/demo-intern-300x242.png",
      "linkedin": "",
    },
    {
      "name": "Merlin Sebastian",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2021/10/Merlin-Sebastian.jpg",
      "linkedin": "https://uk.linkedin.com/in/merlinsebastian15",
    },
    {
      "name": "Rohan",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2021/09/demo-intern-300x242.png",
      "linkedin": "",
    },
    {
      "name": "Trimith chatterjee",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2021/10/Trimith-300x300.jpg",
      "linkedin": "https://in.linkedin.com/in/trimithch",
    },
    {
      "name": "Vishaka Gandhi",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2021/09/demo-intern-300x242.png",
      "linkedin": "",
    },
    {
      "name": "Tara Sreekumar",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2023/02/1665381273193.jpeg",
      "linkedin": "https://www.linkedin.com/in/tara-sreekumar/",
    }
  ],
  "distinguished": [
    {
      "name": "Dr. Amarendra Sahoo",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2020/04/S.-Sridhar.jpg",
      "linkedin": "https://in.linkedin.com/in/amarendrasahoo1956",
    },
    {
      "name": "Mr. Dan Ciuriak",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2020/04/Harsha-Vardhana-Singh.jpg",
      "linkedin": "https://ca.linkedin.com/in/dan-ciuriak-5084601b",
    },
    {
      "name": "Dr. Gopi Munisamy",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2020/05/GopinathMunisamy.jpg",
      "linkedin": "https://www.linkedin.com/in/gopi-munisamy-433a4572",
    },
    {
      "name": "Dr. Harsha Vardhana Singh",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2020/05/HarshaVardhanaSingh.jpg",
      "linkedin": "https://in.linkedin.com/in/harsha-vardhana-singh-54158216",
    },
    {
      "name": "Dr. Hosuk Lee-Makiyama",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2021/03/Hosuk.jpg",
      "linkedin": "https://www.linkedin.com/in/hosuk-lee-makiyama-85547516a/",
    },
    {
      "name": "Dr. Mark Horridge",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2020/04/Mark-Horridge.jpg",
      "linkedin": "https://www.linkedin.com/in/mark-horridge-4b57b91b/",
    },
    {
      "name": "Dr. T. Krishna Kumar",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2020/04/Dan-Ciuriak.jpg",
      "linkedin": "",
    },
    {
      "name": "Dr. Peter B. Dixon",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2020/05/Peter-B-Dixon.jpg",
      "linkedin": "",
    },
    {
      "name": "Dr. S. Sridhar",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2020/05/Sridhar.jpeg",
      "linkedin": "https://in.linkedin.com/in/prof-sridhar-seshadri-ph-d-2533559a",
    },
    {
      "name": "Marinos E Tsigas",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2023/06/WhatsApp-Image-2023-06-21-at-23.48.07.jpg",
      "linkedin": "https://www.linkedin.com/in/marinos-e-tsigas-1b60769b/",
    },
    {
      "name": "Vivien Singer",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2024/02/1554837586683.jpg",
      "linkedin": "https://www.linkedin.com/in/vivien-singer-economist/",
    },
    {
      "name": "Jane Drake Brockman",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2024/03/1560502777161.jpg",
      "linkedin": "https://www.linkedin.com/in/jane-drake-brockman-a4538b5b",
    },
    {
      "name": "David Pickeral",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2024/07/1663532741549.jpeg",
      "linkedin": "https://www.linkedin.com/in/pickeral/",
    },
    {
      "name": "Madhu (Agarwal) Dubhashi",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2024/10/1612840358231.jpeg",
      "linkedin": "https://www.linkedin.com/in/madhu-dubhashi-907aab21/",
    }
  ],
  "advisors": [
    {
      "name": "Dr. Aaron Shew",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2020/05/advisors-1.jpg",
      "linkedin": "https://www.linkedin.com/in/aaron-m-shew/",
    },
    {
      "name": "Mr. Ali Dadkhah",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2020/05/advisors-2.jpg",
      "linkedin": "https://www.linkedin.com/in/ali-dadkhah-597ab524/",
    },
    {
      "name": "Dr. Alicia English",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2020/05/adivsor-3.jpg",
      "linkedin": "https://www.linkedin.com/in/alicia-english-2135a58/",
    },
    {
      "name": "Mr. Ashutosh Yadav",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2021/10/Ashutosh.jpg",
      "linkedin": "https://linkedin.com/in/ashutosh-yadav-a181b08b",
    },
    {
      "name": "Mr. R K Anand",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2020/05/advisors-4.jpg",
      "linkedin": "https://www.linkedin.com/in/r-k-anand-9101415/",
    },
    {
      "name": "Dr. Astha Sen",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2020/06/0-3.jpg",
      "linkedin": "https://www.linkedin.com/in/astha-sen-economist/",
    },
    {
      "name": "Ms. Aanchal Jain",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2020/06/AnchaalJain.jpg",
      "linkedin": "https://www.linkedin.com/in/anchaljn583/",
    },
    {
      "name": "Dr. Ankita Mishra",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2020/05/advisors-05.jpg",
      "linkedin": "https://www.linkedin.com/in/ankita-mishra-a8422b17/",
    },
    {
      "name": "Mr. Amlan Ray",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2021/04/1517708998899.jpg",
      "linkedin": "https://www.linkedin.com/in/amlan-ray-b259064/",
    },
    {
      "name": "Dr. Amrita Saha",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2022/02/Amrita_Saha_March19_A_307-300x300-1.jpg",
      "linkedin": "https://linkedin.com/in/amritasahaeconomist",
    },
    {
      "name": "Ms. Bhawna A.",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2021/08/1617386001429.jpg",
      "linkedin": "https://www.linkedin.com/in/blessedbhawna/",
    },
    {
      "name": "Mr. Balaji Sriraghavan",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2020/04/advisors-59.jpg",
      "linkedin": "https://www.linkedin.com/in/balasriraghavan/",
    },
    {
      "name": "Dr. Binu Devasahayam",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2020/12/1553867266853.jpg",
      "linkedin": "https://www.linkedin.com/in/binukumard/",
    },
    {
      "name": "Dr. Biswajit Nag",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2020/08/biswajitnag.jpg",
      "linkedin": "https://www.linkedin.com/in/biswajitnag/",
    },
    {
      "name": "Dr. Chandra Kiran B Krishnamurthy",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2020/05/advisors-08.jpg",
      "linkedin": "https://se.linkedin.com/in/chandra-kiran-krishnamurthy-5739aa5",
    },
    {
      "name": "Dr. N. Chandrasekhar",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2020/05/advisors-09.png",
      "linkedin": "",
    },
    {
      "name": "Dr. Chidambaran G Iyer",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2020/05/advisors-10.png",
      "linkedin": "https://www.linkedin.com/in/chidambaran-iyer-b186511/",
    },
    {
      "name": "Dr. Chandreyee Namhata",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2020/06/ChandrayeeNamhata-e1593422504172.jpg",
      "linkedin": "https://www.linkedin.com/in/chandreyee-namhata/",
    },
    {
      "name": "Ms. Deepika Wadhwa",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2020/05/advisors-11.jpg",
      "linkedin": "https://www.linkedin.com/in/deepika-w-40a69117/",
    },
    {
      "name": "Dr. Durgesh Chandra Pathak",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2020/05/advisors-12.jpg",
      "linkedin": "https://www.linkedin.com/in/durgeshchandrapathak/",
    },
    {
      "name": "Mr. Dwijendranath Dwivedi",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2020/08/Mr.-Dwijendranath-Dwivedi.jpg",
      "linkedin": "https://www.linkedin.com/in/dwijendra-dwivedi-cqf-prm-4a5b664/",
    },
    {
      "name": "Dr. Dileep Birur",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2020/06/DileepBirur.jpg",
      "linkedin": "https://www.linkedin.com/in/dileep-birur-0346b15/",
    },
    {
      "name": "Mr. Deepak Khatri",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2020/06/DeepakKhatri-1.jpg",
      "linkedin": "https://www.linkedin.com/in/deepak-khatri-7126606/",
    },
    {
      "name": "Dr. Gouranga Das",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2020/05/advisors-14.jpg",
      "linkedin": "https://www.linkedin.com/in/gouranga-das-3555074b/",
    },
    {
      "name": "Dr. Hugo Rojas Romagosa",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2020/05/advisors-15.jpg",
      "linkedin": "https://www.linkedin.com/in/hugo-rojas-romagosa-273632130/",
    },
    {
      "name": "Dr. Hanna C. Norberg",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2020/08/Dr.Hanna_.jpg",
      "linkedin": "https://www.linkedin.com/in/hanna-c-norberg-87055128/",
    },
    {
      "name": "Dr. Issi Romem",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2020/05/advisors-16.jpg",
      "linkedin": "https://www.linkedin.com/in/iromem/",
    },
    {
      "name": "Dr. Isha Jaswal",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2020/05/advisors-17.jpg",
      "linkedin": "https://www.linkedin.com/in/isha-jaswal-5a365218/",
    },
    {
      "name": "Dr. Kamal Gupta",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2020/08/KamalGupta.png",
      "linkedin": "https://www.linkedin.com/in/gargkamal009/",
    },
    {
      "name": "Dr. Krishnan M",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2021/10/1517688052499-1.jpg",
      "linkedin": "https://linkedin.com/in/m-krishnan-b4b358a",
    },
    {
      "name": "Mr. Krishna Srinivasan",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2020/05/advisors-18.jpg",
      "linkedin": "https://www.linkedin.com/in/krishnasrini/",
    },
    {
      "name": "Mr. Frank Curran",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2020/05/advisors-13.jpg",
      "linkedin": "https://www.linkedin.com/in/frank-curran-5b820/",
    },
    {
      "name": "Dr. Lekshmi Nair",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2020/05/advisors-19.jpg",
      "linkedin": "https://www.linkedin.com/in/-lekshmi-r-nair/",
    },
    {
      "name": "Ms. Meenakshi Kothapalli",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2021/09/image_6487327-1.jpg",
      "linkedin": "https://www.linkedin.com/in/meenakshi-kothapalli-52442216/",
    },
    {
      "name": "Dr. Majed Barjas Alrogi",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2020/05/advisors-20.jpg",
      "linkedin": "https://www.linkedin.com/in/majed-b-almubarak-phd-%E9%A9%AC%E5%8D%83%E9%87%8C-734baa72/",
    },
    {
      "name": "Dr. Muhammad Aamir Khan",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2020/05/advisors-24.jpg",
      "linkedin": "https://www.linkedin.com/in/muhammad-aamir-khan/",
    },
    {
      "name": "Dr. Mita Chakraborty",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2020/05/advisors-22.jpg",
      "linkedin": "https://www.linkedin.com/in/mita-chakraborty-14562713/",
    },
    {
      "name": "Mr. Mohammed Naser Al Rajeh",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2020/05/advisors-23.jpg",
      "linkedin": "https://www.linkedin.com/in/mohammed-alrajeh-56647718/",
    },
    {
      "name": "Mr. Mike Snyder",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2020/05/advisors-21.jpg",
      "linkedin": "https://www.linkedin.com/in/ifest/",
    },
    {
      "name": "Dr. Nilanjan Banik",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2021/07/1516893362856.jpg",
      "linkedin": "https://www.linkedin.com/in/nilanjan-banik-54311656/",
    },
    {
      "name": "Dr. Naveen Reddy Kadasala",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2020/05/advisors-25.jpg",
      "linkedin": "https://www.linkedin.com/in/naveen-reddy-kadasala-ph-d-274aaa2a/",
    },
    {
      "name": "Ms. Nathalie Chaloin",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2020/06/Nathalie-Chaloin.jpg",
      "linkedin": "https://www.linkedin.com/in/nathalie-chaloin-mba-728a5718/",
    },
    {
      "name": "Dr. Parneet Kaur Bhangu",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2020/05/advisors-29.jpg",
      "linkedin": "https://www.linkedin.com/in/parneetbhangu/",
    },
    {
      "name": "Ms. Pankhuri Manoj Bansal",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2020/05/advisors-28.jpg",
      "linkedin": "https://www.linkedin.com/in/pankhuri-bansal-54097318/",
    },
    {
      "name": "Dr. Poonam Singh",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2020/05/advisors-30.jpg",
      "linkedin": "https://www.linkedin.com/in/poonam-mehra-singh-phd-4581b312/",
    },
    {
      "name": "Dr. Peeyush Varshney",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2020/08/Peeyush.jpg",
      "linkedin": "https://www.linkedin.com/in/peeyushvarshney/",
    },
    {
      "name": "Dr. Palanisami K",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2020/05/advisors-27.jpg",
      "linkedin": "https://www.linkedin.com/in/palanisami-k-4708029a/",
    },
    {
      "name": "Mr. Ritesh Kumar Singh",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2020/05/advisors-35.jpg",
      "linkedin": "https://www.linkedin.com/in/riteshbusinesseconomist/",
    },
    {
      "name": "Mr. Rajesh Mehta",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2020/05/advisors-33.jpg",
      "linkedin": "https://www.linkedin.com/in/rajeshmehtaentryindia/",
    },
    {
      "name": "Ms. Ridhima Sodhi",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2020/05/advisors-34.jpg",
      "linkedin": "https://www.linkedin.com/in/ridhimasodhi/",
    },
    {
      "name": "Mr. Ramasubramanian Vaidhyanathan",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2022/02/download-_1_.jpg",
      "linkedin": "https://linkedin.com/in/ramasubramanian-vaidhyanathan-85abb241",
    },
    {
      "name": "Dr. Rodrigo Mesa- Arango",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2020/05/advisors-36.jpg",
      "linkedin": "https://www.linkedin.com/in/mesaarangorodrigo/",
    },
    {
      "name": "Dr. Raymond Davies",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2020/09/Dr.Raymond.jpg",
      "linkedin": "https://www.linkedin.com/in/dr-raymond-davies-943881190/",
    },
    {
      "name": "Dr. Sangeeta Khorana",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2020/05/advisors-38.jpg",
      "linkedin": "https://www.linkedin.com/in/sangeeta-khorana-71131a26/",
    },
    {
      "name": "Dr. Subhajit Chakrabarty",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2020/05/advisors-48.jpg",
      "linkedin": "https://www.linkedin.com/in/chakrabarty/",
    },
    {
      "name": "Dr. Saswati Paul",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2020/05/advisors-39.jpg",
      "linkedin": "",
    },
    {
      "name": "Mr. Sivaramakrishnan R",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2020/06/Sivaramakrishnan-R.jpg",
      "linkedin": "https://www.linkedin.com/in/sivaramakrishnan-r-37b28a12/",
    },
    {
      "name": "Mr. SomaSundaram G",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2020/05/advisors-45.jpg",
      "linkedin": "https://www.linkedin.com/in/somasundaramg/",
    },
    {
      "name": "Dr. Surendar Singh",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2020/05/advisors-49.jpg",
      "linkedin": "https://www.linkedin.com/in/dr-surendar-singh-nandha-524b3971/",
    },
    {
      "name": "Mr. Surya Dev Prakash",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2020/05/advisors-51.jpg",
      "linkedin": "https://www.linkedin.com/in/suryadevprakash/",
    },
    {
      "name": "Mr. SivaSubramanian K",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2020/05/advisors-42.jpg",
      "linkedin": "https://www.linkedin.com/in/ksivasubramani/",
    },
    {
      "name": "Dr. Sasidaran Gopalan",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2020/05/advisors-37.jpg",
      "linkedin": "https://www.linkedin.com/in/sasidaran-gopalan-05540148/",
    },
    {
      "name": "Dr. Shagufta Gupta",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2021/07/1617495946935.jpg",
      "linkedin": "https://www.linkedin.com/in/shagufta-gupta-phd-5840764/",
    },
    {
      "name": "Dr. Surabhi Mittal",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2020/05/advisors-50.jpg",
      "linkedin": "https://www.linkedin.com/in/surabhimittal/",
    },
    {
      "name": "Dr. Somnath Hazra",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2020/05/advisors-44.jpg",
      "linkedin": "https://www.linkedin.com/in/somnath-hazra-082bb263/",
    },
    {
      "name": "Ms. Somya Mathur",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2020/05/advisors-47.jpg",
      "linkedin": "https://www.linkedin.com/in/somya-mathur-73a252142/",
    },
    {
      "name": "Ms. Swapna Nair",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2020/05/advisors-46.jpg",
      "linkedin": "https://www.linkedin.com/in/swapna-nair-a800b04/",
    },
    {
      "name": "Dr. Sreekanth Venkataraman",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2021/01/1600184110885.jpeg",
      "linkedin": "https://www.linkedin.com/in/sreekanthv30/",
    },
    {
      "name": "Mr. Suvayan Neogi",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2022/02/48603-26401.jpg",
      "linkedin": "https://linkedin.com/in/suvayan-neogi-50b9a14a",
    },
    {
      "name": "Mr. Thiyagaraj Rangasamy",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2020/05/advisors-52.jpg",
      "linkedin": "https://www.linkedin.com/in/thiyagaraj-rangasamy-2092971a/",
    },
    {
      "name": "Mr. Satyanarayana MR",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2021/08/1613800075628-e1630068569995.jpg",
      "linkedin": "https://www.linkedin.com/in/mrsatyanarayana/",
    },
    {
      "name": "Dr. Sivaramane N",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2021/10/sivaramen.jpg",
      "linkedin": "https://linkedin.com/in/sivaramane-n-218a3723",
    },
    {
      "name": "Mr. Tony Nash",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2020/05/advisors-53.jpg",
      "linkedin": "https://www.linkedin.com/in/tonynash/",
    },
    {
      "name": "Dr. Tavishi Tewary",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2020/08/Tavishi.jpg",
      "linkedin": "https://www.linkedin.com/in/tavishi-tewary-1847b138/",
    },
    {
      "name": "Dr. Zeynep Burcu Irfanoglu",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2020/04/Manitra.jpg",
      "linkedin": "https://www.linkedin.com/in/zeynep-burcu-irfanoglu-1906b136/",
    },
    {
      "name": "Ms. Usha Rengaraju",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2020/06/UshaRengaraju.jpg",
      "linkedin": "https://www.linkedin.com/in/usha-rengaraju-b570b7a2/",
    },
    {
      "name": "Mr.Vijay Bhalaki",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2020/10/Vijai.jpg",
      "linkedin": "https://linkedin.com/in/vijay-bhalaki-46297913",
    },
    {
      "name": "Dr. Valijon Turakulov",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2021/06/Valijon-Turakulov.jpg",
      "linkedin": "https://www.linkedin.com/in/vturakulov/",
    },
    {
      "name": "Dr. Vinod Mishra",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2020/05/advisors-54.jpg",
      "linkedin": "https://www.linkedin.com/in/ivinodmishra/",
    },
    {
      "name": "Sanghita Mondal",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2023/01/1516430910913.jpg",
      "linkedin": "https://www.linkedin.com/in/sanghitamondal/",
    },
    {
      "name": "Dr. Jyoti Tripathi",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2023/01/WhatsApp-Image-2023-01-23-at-13.55.56-1.jpg",
      "linkedin": "https://www.linkedin.com/in/jyoti-tripathi-521b2615/",
    },
    {
      "name": "Dr. Sukanya Das",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2022/10/1637772981775.jpg",
      "linkedin": "https://www.linkedin.com/in/sukanya-das-61519a17/",
    },
    {
      "name": "Dr. Nidhi Gupta",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2022/10/1643856315088.jpeg",
      "linkedin": "https://www.linkedin.com/in/dr-nidhi-gupta-58902110/",
    },
    {
      "name": "Pratima P.",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2023/01/1668572611563.jpg",
      "linkedin": "https://www.linkedin.com/in/conserveenvironment/",
    },
    {
      "name": "Dr. Meenal Sharma Jagtap",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2023/03/1621277752161.jpeg",
      "linkedin": "https://www.linkedin.com/in/dr-meenal-sharma-jagtap-63040a28/",
    },
    {
      "name": "Ashish Sedia",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2023/02/1526247462362.jpeg",
      "linkedin": "https://www.linkedin.com/in/ashish-sedai-94b01847/",
    },
    {
      "name": "Dr. Megha Jain",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2023/02/1660375031381.jpeg",
      "linkedin": "https://www.linkedin.com/in/dr-megha-jain-2a480752/",
    },
    {
      "name": "Rama Kamaraju",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2023/02/1675819006331.jpeg",
      "linkedin": "https://www.linkedin.com/in/rama-kamaraju-46709818/",
    },
    {
      "name": "Dr. Parashram Patil",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2023/03/1571926865770.jpg",
      "linkedin": "https://www.linkedin.com/in/dr-parashram-patil-5ba6a43b/",
    },
    {
      "name": "Arjit Bhargava",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2023/07/1678092941277.jpeg",
      "linkedin": "https://www.linkedin.com/in/arjitbhargava/",
    },
    {
      "name": "Jwalant Desai",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2023/03/1614833533351.jpeg",
      "linkedin": "https://www.linkedin.com/in/jwalant-desai-8731589/",
    },
    {
      "name": "Raghunandan Akur Raman",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2023/04/1655057941411.jpeg",
      "linkedin": "https://www.linkedin.com/in/raghunandan-akur-raman-979a35b/",
    },
    {
      "name": "H. S. Panaser",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2023/04/WhatsApp-Image-2023-04-23-at-22.04.53-1.jpg",
      "linkedin": "https://www.linkedin.com/in/panaser/",
    },
    {
      "name": "Geetha malini R",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2023/06/1657737479085.jpg",
      "linkedin": "https://www.linkedin.com/in/geetha-malini-r-14208968/",
    },
    {
      "name": "Praveen P A",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2023/08/1605617262867.jpeg",
      "linkedin": "https://www.linkedin.com/in/praveenpa",
    },
    {
      "name": "Ramya Grama",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2023/07/WhatsApp-Image-2023-07-05-at-09.42.37-1.jpg",
      "linkedin": "https://www.linkedin.com/in/ramyagrama/",
    },
    {
      "name": "Hussain Alhatem",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2023/07/1688939504949.jpeg",
      "linkedin": "https://www.linkedin.com/in/hussain-alhatem/",
    },
    {
      "name": "Ganapathi Nagarajan",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2023/08/g-nag-1.jpg",
      "linkedin": "https://www.linkedin.com/in/ganapathi-nagarajan-2b60aa89/",
    },
    {
      "name": "Subir Dhar",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2023/08/1516161334467.jpeg",
      "linkedin": "https://www.linkedin.com/in/subirdhar",
    },
    {
      "name": "Dr. Suvajit Banerjee",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2023/11/Mr._Suvajit_Banerjee.jpg",
      "linkedin": "https://www.linkedin.com/in/dr-suvajit-banerjee-305172117/",
    },
    {
      "name": "Anand Pandey",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2023/08/1517662657152.jpeg",
      "linkedin": "https://www.linkedin.com/in/pandeyanand",
    },
    {
      "name": "Pasakorn Thammachote",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2023/08/1627658787229-1.jpeg",
      "linkedin": "https://www.linkedin.com/in/pasakorn-thammachote-249761218",
    },
    {
      "name": "Aman Chahal",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2023/09/aman-chahal.jpg",
      "linkedin": "https://www.linkedin.com/in/cleantecher/",
    },
    {
      "name": "Chandan Kumar J.",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2023/10/1516605621581.jpeg",
      "linkedin": "https://www.linkedin.com/in/chandan-kumar-j-9916ab16/",
    },
    {
      "name": "Rajesh Rajamohanan Nair",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2024/07/1704224087119.jpeg",
      "linkedin": "https://www.linkedin.com/in/faangtpm/",
    },
    {
      "name": "Dr.Kabaly P Subramanian",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2024/05/1671565490118.jpeg",
      "linkedin": "https://www.linkedin.com/in/dr-kabaly-p-subramanian-phd-fcmi-uk-cmbe-uk-13b4465/",
    },
    {
      "name": "Swadhin Mondal",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2024/05/1516512008256.jpeg",
      "linkedin": "https://www.linkedin.com/in/swadhin-mondal-12084713",
    },
    {
      "name": "Vranda Jain",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2024/06/VRANDA-JAIN.jpg",
      "linkedin": "https://www.linkedin.com/in/vranda-jain-ph-d-51807115b/",
    },
    {
      "name": "T Kumar",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2024/05/1595949774823.jpeg",
      "linkedin": "https://www.linkedin.com/in/t-kumar-5b38658/",
    },
    {
      "name": "Dr. Javeria M.",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2024/10/1722522944210.jpeg",
      "linkedin": "https://www.linkedin.com/in/dr-javeria-maryam/",
    },
    {
      "name": "Tariq Aziz",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2024/07/1516980930251.jpeg",
      "linkedin": "https://www.linkedin.com/in/tariqazizsial/",
    },
    {
      "name": "Nader Khalifa",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2024/07/download-4.jpeg",
      "linkedin": "https://www.linkedin.com/in/nader-khalifa-5297a316",
    },
    {
      "name": "Kali Prasad",
      "role": "",
      "image": "https://infisum.com/wp-content/uploads/2020/05/images-e1589196433162.jpg",
      "linkedin": "https://www.linkedin.com/in/kali-prasad-9675377",
    }
  ]
};

